import { nodejs } from "@vllnt/eslint-config/nodejs";

export default [
  {
    ignores: [
      ".tmp/**",
      ".worktrees/**",
      "dist/**",
      "eslint.config.js",
      "node_modules/**",
      "package-lock.json",
      "pnpm-lock.yaml",
      "scripts/**/*.mjs",
      "tests/**/*.mjs",
    ],
  },
  ...nodejs,
  {
    files: ["index.ts", "src/**/*.ts"],
    rules: {
      "@typescript-eslint/consistent-type-definitions": "off",
      "@typescript-eslint/naming-convention": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
      "@typescript-eslint/no-dynamic-delete": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-redundant-type-constituents": "off",
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
      "@typescript-eslint/no-unnecessary-type-parameters": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/require-await": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/switch-exhaustiveness-check": "off",
      "@typescript-eslint/use-unknown-in-catch-callback-variable": "off",
      "functional/functional-parameters": "off",
      "functional/no-loop-statements": "off",
      "max-depth": "off",
      "max-lines-per-function": "off",
      "max-params": "off",
      "no-restricted-syntax": "off",
      "perfectionist/sort-union-types": "off",
      "unicorn/catch-error-name": "off",
      "unicorn/consistent-function-scoping": "off",
      "unicorn/no-array-method-this-argument": "off",
      "unicorn/no-nested-ternary": "off",
      "unicorn/no-null": "off",
      "unicorn/no-process-exit": "off",
      "unicorn/no-useless-undefined": "off",
      "unicorn/prefer-logical-operator-over-ternary": "off",
      "unicorn/prefer-top-level-await": "off",
      "unicorn/prevent-abbreviations": "off",
      "unicorn/switch-case-braces": "off",
      "write-good-comments/write-good-comments": "off",
    },
  },
];
